services:

  postgres:
    image: postgres:16
    container_name: smarthome-postgres

    environment:
      POSTGRES_DB: smarthome
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smarthome"]
      interval: 5s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: ./backend

    container_name: smarthome-backend

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smarthome
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8081

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8081:8081"


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api/readings

    container_name: smarthome-frontend

    depends_on:
      - backend

    ports:
      - "8080:80"


volumes:
  postgres_data:
